### ISSUE TITLE
Incompatible with other SilverShop modules

### ISSUE THREAD

**Issue by christopherbolt** [xini/silverstripe-silvershop-stripe#1]
The requirement for your silvershop/core dev-merged repository version makes this difficult to install if you are using other SilverShop modules such as silvershop/discounts, silvershop/shipping etc as these require silvershop/core ^3

composer displays:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - silvershop/shipping 2.x-dev requires silvershop/core ^3 -> satisfiable by silvershop/core[3.x-dev].
    - silvershop/shipping 2.x-dev requires silvershop/core ^3 -> satisfiable by silvershop/core[3.x-dev].
    - silvershop/shipping 2.x-dev requires silvershop/core ^3 -> satisfiable by silvershop/core[3.x-dev].
    - don't install silvershop/core dev-merged|remove silvershop/core 3.x-dev
    - don't install silvershop/core 3.x-dev|don't install silvershop/core dev-merged
    - don't install silvershop/core dev-merged|don't install silvershop/core 3.x-dev
    - don't install silvershop/core 3.x-dev|don't install silvershop/core dev-merged
    - Installation request for silvershop/core dev-merged -> satisfiable by silvershop/core[dev-merged].
    - Installation request for silvershop/shipping (locked at 2.x-dev, required as master) -> satisfiable by silvershop/shipping[2.x-dev].

**Comment by xini** [comment]
You can use the following workaround to install the module and make composer accept the custom repository (see [composer docs](https://getcomposer.org/doc/articles/aliases.md#require-inline-alias)):

```
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/xini/silvershop-core"
    }
],
"require": {
    "silvershop/core": "dev-merged as 3.x-dev"
}
```

In the meantime, my two pull requests have been accepted by the main repo though. You no can just remove the custom repository and require 3.x-dev from the main repo. I will update the module asap.
