### ISSUE TITLE
Checkout form not redirecting to payment page

### ISSUE THREAD

**Issue by joshdillner** [xini/silverstripe-silvershop-stripe#5]
Hi, for anyone else who comes across this issue - I had to add `is_offsite: false` to the `SilverStripe\Omnipay\GatewayInfo:Stripe` config.

**Comment by xini** [comment]
Hi Josh,
Thanks for this. Can you tell me what exactly the issue was you were having? I can't reproduce an error. 
Thanks

**Comment by joshdillner** [comment]
@xini on clicking "proceed to payment" I'd just get an error saying "credit card number required". I guess this is more a case of Silvershop incorrectly seeing Stripe as an offsite payment gateway through the `omnipay/stripe` module.

**Comment by innomedia** [comment]
> Hi, for anyone else who comes across this issue - I had to add `is_offsite: false` to the `SilverStripe\Omnipay\GatewayInfo:Stripe` config.

Thanks man. You just saved me hours of searching

**Comment by xini** [comment]
Hi @joshdillner, 
Thanks for this. 
I have added the config to the default config of the module.
Cheers

**Comment by joshdillner** [comment]
Cheers @xini
