### ISSUE TITLE
php-http/guzzle6-adapter version

### ISSUE THREAD

**Issue by sparkcom** [xini/silverstripe-silvershop-stripe#6]
Hello

wonder if you could update the composer package so that  php-http/guzzle6-adapter:2.2.0  is required? when i run 

composer i got the following 
`Using version ^1.0@beta for innoweb/silverstripe-silvershop-stripe
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install innoweb/silverstripe-silvershop-stripe 1.0.0-beta3
    - Conclusion: don't install innoweb/silverstripe-silvershop-stripe 1.0.0-beta2
    - Conclusion: remove php-http/guzzle6-adapter v2.0.1
    - Installation request for innoweb/silverstripe-silvershop-stripe ^1.0@beta -> satisfiable by innoweb/silverstripe-silvershop-stripe[1.0.0-beta1, 1.0.0-beta2, 1.0.0-beta3].`

**Comment by xini** [comment]
Hi @sparkcom 
Thanks for this. I had a look at this and it turns out the module doesn't need guzzle anymore. I have removed this obsolete dependency in beta 4.
Cheers
