### ISSUE TITLE
Stripe Payment Intents

### ISSUE THREAD

**Issue by MatMorrisParker** [xini/silverstripe-silvershop-stripe#7]
Are there any plans to upgrade this to support Stripe Payment Intents (or is there a way to enable it that I've missed)?

**Comment by xini** [comment]
Hi Mathew,
I don't have any plans for this just yet. But certainly sounds reasonable. 
Happy to accept PRs if you want to have a go at it?
Cheers

**Comment by MatMorrisParker** [comment]
Thanks for the swift response @xini ! I'm happy to give it a go, although I'll be honest I'm not entirely confident I'll be of much use

Do you have any pointers of what would need to be updated?

**Comment by xini** [comment]
@wernerkrauss and @BettinaMaria98 I believe you have implemented payment intends in a fork of this module? Is that something we could merge back? Cheers

**Comment by xini** [comment]
https://github.com/BettinaMaria98/silverstripe-silvershop-stripe/tree/paymentintents

**Comment by BettinaMaria98** [comment]
@xini Yes we think that it could merged back, I opened a pull request to get our changes back to your module!
https://github.com/xini/silverstripe-silvershop-stripe/pull/10/

**Comment by xini** [comment]
@BettinaMaria98 thank you very much, how exciting! I believe your changes are fully backwards compatible? Or do we need a new major version?

**Comment by BettinaMaria98** [comment]
@wernerkrauss what do you think?

**Comment by xini** [comment]
implemented in #10. Thanks @BettinaMaria98 and @wernerkrauss
