### ISSUE TITLE
Error when editing/deleting users in admin security after install

### ISSUE THREAD

**Issue by sfimedia** [xini/silverstripe-silvershop-stripe#9]
[Emergency] Uncaught Omnipay\Common\Exception\InvalidRequestException: The customerReference parameter is required
GET /admin/security/EditForm/field/Members/item/13/edit?gridState-Members-0=%7B%22GridFieldSortableHeader%22%3A%7B%22SortColumn%22%3A%5B%5D%7D%2C%22GridFieldFilterHeader%22%3A%7B%22Columns%22%3Anull%7D%2C%22GridFieldPaginator%22%3A%7B%22currentPage%22%3A1%2C%22itemsPerPage%22%3A15%7D%7D

Line 81 Projects/httpdocs/vendor/omnipay/common/src/Common/ParametersTrait.php

**Comment by xini** [comment]
Thanks for reporting this. Fixed and tagged as 1.0.0-beta6.
